version: "3"
services: 
  api: 
    build: ./api
    ports: 
      - '3000:3000'
    volumes: 
      - './api:/usr/src/app'
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    # db作成後にコンテナ作成
    depends_on: 
      - db
  db: 
    image: postgres
    volumes: 
      - ./db/data:/var/lib/postgresql/data
    environment: 
      POSTGRES_PASSWORD: password
  app: 
    build: ./front
    volumes: 
      - ./front/app:/usr/src/app
    ports: 
      - "8080:3000"
    command: "yarn start"
    stdin_open: true
    environment: 
      - CHOKIDAR_USEPOLLING=true
