version: "3"
services:
  app:
    build:
      context: .
    volumes:
      - ./app:/usr/src/app
    ports:
      - "8080:3000"
    command: "yarn start"
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
